### ISSUE TITLE
responsive layout gaps

### ISSUE THREAD

**Issue by emersonthis** [inuitcss/objects.layout#9]
Are the various layout gap settings intended to work with the responsive breakpoint modifiers? For example, the `.layout__item`s accept different width classes: `.layout__item palm-1/2 lap-and-up-1/4`. I'm trying to figure out if there is a way to do this for the `.layout--<size> ` classes. Hypothetically: `layout-palm--small layout-lap-and-up--large`. Is there already a way to do this? If not, should there be?

**Comment by florianbouvot** [comment]
There is no solution in current layout object.

*In my opinion, it's not a good idea to include this in inuit because it will increase complexity... (every modifiers from every objects will "need" responsive options).*

But you can add it in your own code ;)

**Comment by s-d-p** [comment]
I don't think I understand what you mean? Why would they all "need" responsive options? Couldn't they just default in the same way the current layout__item classes do when the modifier is omitted? 

Ex: `layout__item 1/2` = `layout__item palm-1/2 lap-1/2 desk-1/2`

How would this feature add more complexity than what we already manage with the `layout__item` responsive options?

Is the main reason you think this is "not a good idea to include in unuit" because it is too hard to do? Or because you don't think this would be useful?

**Comment by florianbouvot** [comment]
I mean that adding responsive modifier for layout gutter open the door for responsive modifier for lot of others objects like `media`, `flag`, `list-block`, `list-ui`, `button`, `block`...

**Comment by s-d-p** [comment]
I guess I see your point. But making the gutter width responsive doesn’t seem random or arbitrary to me at all because it’s directly connected to the responsive options we already support. After all, we already have responsive modifiers on the layout__item. And gutter + layout__item go together like peanut butter and jelly. :-)

**Comment by florianbouvot** [comment]
:D I understand but it's only my opinion. 

Responsive options (inuitcss `widths` and `responsive-widths`) are not specific to `layout__item` it's generic utilities. And responsive gutter will increase inuitcss `layout` dependencies.

**Comment by csshugs** [comment]
You could "fake" your desired behaviour by using [responsive spacings](https://github.com/inuitcss/trumps.spacing-responsive):
```html
<div class="[ layout ]  [ palm--ml- ]">
    <div class="[ layout__item  1/4 ]  [ palm-pl- ]">
        ...
    </div><!--
    --><div class="[ layout__item  1/4 ]  [ palm-pl- ]">
        ...
    </div><!--
    --><div class="[ layout__item  1/4 ]  [ palm-pl- ]">
        ...
    </div><!--
    --><div class="[ layout__item  1/4 ]  [ palm-pl- ]">
        ...
    </div>
</div>
```

This will decrease the `padding-left` of the `.layout__item`s  and the negative `margin-left` of `.layout` on palm. I don't see any downsides of that.

Beyond that I'm with @florianbouvot. I would dislike a overload of this kind in the framework.

**Comment by anselmh** [comment]
Closing this since there’s no broad agreement that this is needed. Thanks for the request/idea though! :)
